### ISSUE TITLE
ModuleNotFoundError: No module named 'PyQt5.sip' 

### ISSUE THREAD

**Issue by moreal** [Team-Lapio/kiwi-steg#6]
```
Traceback (most recent call last):
File ".\main.py", line 4, in <module>                                                                                                                                                             
from package import app                                                                                                                                                                       
File "C:\Users\dsm2017\kiwi-steg\package\app.py", line 1, in <module>                                                                                                                             
from PyQt5 import QtCore, QtGui, QtWidgets                                                                                                                                                  
ModuleNotFoundError: No module named 'PyQt5.sip'
```

**Comment by cxbt** [comment]
Do you have PyQt5 installed in python environment?

**Comment by moreal** [comment]
![image](https://user-images.githubusercontent.com/26626194/49639554-a6f0eb80-fa4e-11e8-898b-e60e54d155be.png)

I see there was the packages

**Comment by sunghun7511** [comment]
Hello cool guy, I have a question for you @moreal. Your issue was crash in a windows platform, but your reply picture seems like run on linux platform. In linux, did you run on same python environment with pip3?
(Btw, how about reference [this one](https://stackoverflow.com/questions/51324754/python-3-6-x-pyinstaller-gives-error-no-module-named-pyqt5-sip)? It will may help for you.)
